spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payment-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:payment}
    password: ${SPRING_DATASOURCE_PASSWORD:payment}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    open-in-view: false

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

resilience4j:
  retry:
    instances:
      externalPaymentProcessor:
        max-attempts: 3
        wait-duration: 500ms

  circuitbreaker:
    instances:
      externalPaymentProcessor:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3

  timelimiter:
    instances:
      externalPaymentProcessor:
        timeout-duration: 2s

  bulkhead:
    instances:
      externalPaymentProcessor:
        max-concurrent-calls: 5
        max-wait-duration: 0

app:
  rabbit:
    exchange:
      order: ${APP_RABBIT_EXCHANGE_ORDER:ex.order}
      payment: ${APP_RABBIT_EXCHANGE_PAYMENT:ex.payment}

    routing-key:
      order-created: ${APP_RABBIT_ROUTING_KEY_ORDER_CREATED:order.created}
      payment-approved: ${APP_RABBIT_ROUTING_KEY_PAYMENT_APPROVED:payment.approved}
      payment-pending: ${APP_RABBIT_ROUTING_KEY_PAYMENT_PENDING:payment.pending}

    queue:
      payment-order-created: ${APP_RABBIT_QUEUE_PAYMENT_ORDER_CREATED:payment.order.created}
      payment-approved-debug: ${APP_RABBIT_QUEUE_PAYMENT_APPROVED_DEBUG:payment.approved.debug}
      payment-pending-debug: ${APP_RABBIT_QUEUE_PAYMENT_PENDING_DEBUG:payment.pending.debug}

    dlq:
      payment-order-created: ${APP_RABBIT_DLQ_PAYMENT_ORDER_CREATED:payment.order.created.dlq}
      payment-approved-debug: ${APP_RABBIT_DLQ_PAYMENT_APPROVED_DEBUG:payment.approved.debug.dlq}
      payment-pending-debug: ${APP_RABBIT_DLQ_PAYMENT_PENDING_DEBUG:payment.pending.debug.dlq}


  payment:
    retry:
      scheduler:
        enabled: true
        fixed-delay-ms: 30000

  external-payment:
    fake-enabled: ${APP_EXTERNAL_PAYMENT_FAKE_ENABLED:false}
    base-url: ${APP_EXTERNAL_PAYMENT_BASE_URL:http://localhost:8089}
    request-path: ${APP_EXTERNAL_PAYMENT_REQUEST_PATH:/requisicao}
    connect-timeout-ms: ${APP_EXTERNAL_PAYMENT_CONNECT_TIMEOUT_MS:1000}
    read-timeout-ms: ${APP_EXTERNAL_PAYMENT_READ_TIMEOUT_MS:2000}

server:
  port: ${SERVER_PORT:8083}
