spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payment-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:payment}
    password: ${SPRING_DATASOURCE_PASSWORD:payment}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:payment-service}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "br.com.fiap.restaurant.payment.infra.messaging.inbound.dto"
        spring.json.value.default.type: "br.com.fiap.restaurant.payment.infra.messaging.inbound.dto.OrderCreatedMessage"

app:
  kafka:
    topics:
      order-created: pedido.criado
      payment-approved: pagamento.aprovado
      payment-pending: pagamento.pendente

server:
  port: ${SERVER_PORT:8083}