spring:
  application:
    name: ${SPRING_APPLICATION_NAME:payment-service}

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/paymentdb}
    username: ${SPRING_DATASOURCE_USERNAME:payment}
    password: ${SPRING_DATASOURCE_PASSWORD:payment}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    open-in-view: false

  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

app:
  rabbit:
    order-exchange: ${APP_RABBIT_ORDER_EXCHANGE:order.exchange}
    payment-exchange: ${APP_RABBIT_PAYMENT_EXCHANGE:payment.exchange}

    order-created-queue: ${APP_RABBIT_ORDER_CREATED_QUEUE:pedido.criado.queue}
    order-created-routing-key: ${APP_RABBIT_ORDER_CREATED_ROUTING_KEY:pedido.criado}

    payment-approved-routing-key: ${APP_RABBIT_PAYMENT_APPROVED_ROUTING_KEY:pagamento.aprovado}
    payment-pending-routing-key: ${APP_RABBIT_PAYMENT_PENDING_ROUTING_KEY:pagamento.pendente}

    approved-debug-queue: ${APP_RABBIT_APPROVED_DEBUG_QUEUE:payment.approved.debug.queue}
    pending-debug-queue: ${APP_RABBIT_PENDING_DEBUG_QUEUE:payment.pending.debug.queue}

server:
  port: ${SERVER_PORT:8083}